source 'https://rubygems.org'

gem 'rails', '4.2.8'
gem 'mysql2', '~> 0.3.18'
gem 'numbers_in_words'
gem 'activerecord-sqlserver-adapter'
gem 'dbi'
gem 'activerecord-session_store'
gem 'mdb'
gem 'ruby-graphviz', '~> 1.2', '>= 1.2.2'
gem 'twilio-ruby', '~> 4.11', '>= 4.11.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'whenever', '~> 0.9.7', :require => false
gem 'geocoder'
gem 'kaminari', '~> 0.16.3'
gem 'coderay'
gem 'bootstrap-datepicker-rails'
gem 'awesome_print'
gem 'datagrid', '~> 1.4', '>= 1.4.1'
gem 'quiet_assets'
gem 'will_paginate'
gem 'fullcalendar-rails', '~> 3.4.0.0'
gem 'momentjs-rails'
gem 'tzinfo-data', '~> 1.2016', '>= 1.2016.10'
gem 'paperclip', '~> 4.3', '>= 4.3.6'
gem 'mime-types-data', '~> 3.2016', '>= 3.2016.0521'
gem 'globalid', '~> 0.3.7'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'json', '~> 1.8', '>= 1.8.3'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'thin', '~> 1.6', '>= 1.6.4'
gem 'bundler'
gem 'delayed_job_active_record'
gem "daemons"
gem 'prawn', '~> 1.3.0'
gem 'pdfkit', '~> 0.8.2'
gem 'rake', '~> 12.0'
gem 'wicked_pdf', '~> 1.1'
gem 'selenium-webdriver', '~> 3.0', '>= 3.0.5'
gem 'wkhtmltopdf-binary', '~> 0.9.9.3'
gem 'bcrypt-ruby', '~> 3.0.0', :require => 'bcrypt'
gem 'bcrypt'
gem 'omniauth'
gem 'omniauth-wsfed', '0.3.2.pre.beta'
gem 'devise'
gem 'cancancan', '~> 1.10'
gem 'apartment'
gem 'local-subdomain'
gem 'bootstrap_form'
gem 'jquery-validation-rails'
gem 'rails-erd'
gem 'protokoll'
gem 'city-state'
gem 'bootstrap3-datetimepicker-rails', '~> 4.0.0'
gem 'jquery-ui-rails'
gem 'time_difference'
gem 'roo'
gem 'yaml_db'
gem 'email_verifier'
gem 'axlsx', '~> 2.0'
gem "axlsx_rails"
gem "chartkick"
gem 'pry'

group :development, :test do
	gem 'byebug'
	gem 'cucumber-rails', :require => false
	gem 'database_cleaner'
end

group :development do
	gem 'web-console', '~> 2.0'
	gem 'table_print'
	gem 'wirble'
	gem 'hirb'
end