development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true
  database: hrms_development
  username: root
  password: kiit
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root  
  password: kiit
  database: hrms_development

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: kiit
  database: hrms_development