development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true
  database: hrms_development
  username: root
  password: kiit

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true
  database: hrms_development
  username: root
  password: kiit

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true
  database: hrms_development
  username: root
  password: kiit
  
development_sec:
  adapter: sqlserver
  encoding: utf8
  pool: 5
  database: Premier
  username: sa
  password: root
  host: 172.16.1.32

production_sec:
  adapter: sqlserver
  encoding: utf8
  pool: 5
  database: Premier
  username: sa
  password: root
  host: 172.16.1.32

test_sec:
  adapter: sqlserver
  encoding: utf8
  pool: 5
  database: Premier
  username: sa
  password: root
  host: 172.16.1.32

#   development_sec:
#   adapter: sqlserver
#   encoding: utf8
#   host: 123.201.35.198
#   database: ZKA
#   username: sa
#   password: pass

# production_sec:
#   adapter: sqlserver
#   encoding: utf8
#   host: 123.201.35.198
#   database: ZKA
#   username: sa
#   password: pass

# test_sec:
#   adapter: sqlserver
#   encoding: utf8
#   host: 123.201.35.198
#   database: ZKA
#   username: sa
#   password: pass

