development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  # socket: /var/run/mysqld/mysqld.sock
  reconnect: true
  database: hrms_development
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  database: hrms_development

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  database: hrms_development


development_sec:
  adapter: sqlserver
  encoding: utf8
  host: 49.248.220.11
  database: myAttendance_web
  username: sa
  password: administrator@123

production_sec:
  adapter: sqlserver
  encoding: utf8
  host: 49.248.220.11
  database: myAttendance_web
  username: sa
  password: administrator@123

test_sec:
  adapter: sqlserver
  encoding: utf8
  host: 49.248.220.11
  database: myAttendance_web
  username: sa
  password: administrator@123


