
development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true
  database: hrms_development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true
  database: hrms_development
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  database: hrms_development

development_sec:
  adapter: sqlserver
  encoding: utf8
  host: 192.168.0.15
  database: etimetracklite1
  username: SA

production_sec:
  adapter: sqlserver
  encoding: utf8
  host: 192.168.0.15
  database: etimetracklite1
  username: SA

test:
  adapter: sqlserver
  encoding: utf8
  host: 192.168.0.15
  database: etimetracklite1
  username: SA
