development:
  adapter: mysql2
  username: root
  password: root
  database: hrms_development

test:
  adapter: mysql2
  database: hrms_development
  username: root
  password: root

production:
  adapter: mysql2
  database: hrms_development
  username: root
  password: root

development_sec:
  adapter: sqlserver
  encoding: utf8
  host: 192.168.2.240
  port: 49310
  database: COSEC
  username: hrms
  password: hrms

test_sec:
  adapter: sqlserver
  encoding: utf8
  host: 192.168.2.240
  port: 49310
  database: COSEC
  username: hrms
  password: hrms

production_sec:
  adapter: sqlserver
  encoding: utf8
  host: 192.168.2.240
  port: 49310
  database: COSEC
  username: hrms
  password: hrms

development_thi:
  adapter: sqlserver
  encoding: utf8
  host: 192.168.1.67
  port: 49310
  database: COSECSAMAY
  username: hrms
  password: Hrms@123

test_thi:
  adapter: sqlserver
  encoding: utf8
  host: 192.168.1.67
  port: 49310
  database: COSECSAMAY
  username: hrms
  password: Hrms@123

production_thi:
  adapter: sqlserver
  encoding: utf8
  host: 192.168.1.67
  port: 49310
  database: COSECSAMAY
  username: hrms
  password: Hrms@123
  

